### ISSUE TITLE
No config options in admin UI

### ISSUE THREAD

**Issue by kaoz70** [bentrynning/strapi-provider-upload-firebase#3]
Hello, this is my first Strapi project so I might be missing something. In the docs you say that we have to go to General → Plugins → Files Upload (⚙) → Select "Firestore" in the Providers section, but using Strapi 3.0.1 that option is not found anywhere:

![image](https://user-images.githubusercontent.com/79406/83951387-ce1caa80-a7f6-11ea-8ce9-a855b55057fb.png)

And I have the upload plugin and Firebase proviers installed:

![image](https://user-images.githubusercontent.com/79406/83951566-ea6d1700-a7f7-11ea-8018-c03350a63506.png)

What I found out according to the [Strapi docs](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider) is that you have to put the Firebase config in the config/plugins.js like this:

    module.exports = ({ env }) => ({
      upload: {
        provider: 'firebase',
        providerOptions: {....firebase options here}
    });

So the problem with this is that your plugin is waiting for a JSON string and not a JS object.

![image](https://user-images.githubusercontent.com/79406/83951593-18eaf200-a7f8-11ea-81aa-638adb6f5e1f.png)

And of course this generates an error.

Checking the S3 provider we can see that the data is passed directly:

![image](https://user-images.githubusercontent.com/79406/83951585-0f618a00-a7f8-11ea-81b4-f013dec602a9.png)

**Comment by malnakli** [comment]
I have rewritten it: https://gist.github.com/malnakli/8f353bc0765f2bf5fcef11f27e01158d

Then  in `config/plugins.js`
```js
module.exports = ({ env }) => ({
  upload: {
    provider: "firebase",
    providerOptions: {
      serviceAccount: {
        type: "service_account",
        project_id: env("FIREBASE_PROJECT_ID"),
        private_key_id: env("FIREBASE_PRIVATE_KEY_ID"),
        private_key: env("FIREBASE_PRIVATE_KEY"),
        client_email: env("FIREBASE_PRIVATE_CLIENT_EMAIL"),
        client_id: env("FIREBASE_PRIVATE_CLIENT_ID"),
        auth_uri: "https://accounts.google.com/o/oauth2/auth",
        token_uri: "https://oauth2.googleapis.com/token",
        auth_provider_x509_cert_url:
          "https://www.googleapis.com/oauth2/v1/certs",
        client_x509_cert_url:
          "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-bwdkz%40xxxx.iam.gserviceaccount.com",
      },
      bucket: "xxxx.appspot.com",
    },
  },
});
```

**Comment by kaoz70** [comment]
Yeah, that worked! It would be great that this could be published to NPM

**Comment by nearby76000** [comment]
hello the don't work for me.
I instal the package and i crate in extension folder upload/config/setting.js

and i past your code with my data
module.exports = ({ env }) => ({
  upload: {
    provider: "firebase",
    providerOptions: {
      serviceAccount: {
        type: "service_account",
        project_id: env("FIREBASE_PROJECT_ID"),
        private_key_id: env("FIREBASE_PRIVATE_KEY_ID"),
        private_key: env("FIREBASE_PRIVATE_KEY"),
        client_email: env("FIREBASE_PRIVATE_CLIENT_EMAIL"),
        client_id: env("FIREBASE_PRIVATE_CLIENT_ID"),
        auth_uri: "https://accounts.google.com/o/oauth2/auth",
        token_uri: "https://oauth2.googleapis.com/token",
        auth_provider_x509_cert_url:
          "https://www.googleapis.com/oauth2/v1/certs",
        client_x509_cert_url:
          "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-bwdkz%40xxxx.iam.gserviceaccount.com",
      },
      bucket: "xxxx.appspot.com",
    },
  },
});

but it d'ont work

**Comment by malnakli** [comment]
You need to paste the code in `config/plugins.js`
